apiVersion: v1
kind: ConfigMap
metadata:
  name: fx-game-config
data:
  DATA_PATH: /data/ # Trailing / makes this mort portable, will work with os.path.join and '+'
  RESET_SCORE_ON_STARTUP: "true"
  # When the app pod and the service using the global static ip run on the same namespace
  # then the IP address can be replaced by the service name, the pod will map it to the address.
  TRADING_SERVER: "fx-game-service"
  TRADING_SERVER_PORT: "443"
  SECRET: "Hackathon24-secret"